import{a as S,S as q,i as n}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const M="51455411-f57f23fa62a07ae8b27dc37d3",P="https://pixabay.com/api/";async function m(t,r=1,i=15){const a={key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:i};try{return(await S.get(P,{params:a})).data}catch{throw new Error("Failed to fetch images from Pixabay")}}const f=document.querySelector(".gallery"),h=document.querySelector(".main-loader"),g=document.querySelector(".load-more-loader"),E=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(t){const r=t.map(({webformatURL:i,largeImageURL:a,tags:e,likes:o,views:s,comments:w,downloads:v})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${i}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${w}</p>
        <p><b>Downloads:</b> ${v}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",r),E.refresh()}function R(){f.innerHTML=""}function $(){h.classList.remove("is-hidden")}function x(){h.classList.add("is-hidden")}function A(){g.classList.remove("is-hidden")}function I(){g.classList.add("is-hidden")}function O(t){t&&t.parentElement.classList.remove("is-hidden")}function y(t){t&&t.parentElement.classList.add("is-hidden")}const L=document.querySelector(".form"),d=document.querySelector(".load-more");let l="",c=1;const u=15;let b=0;L.addEventListener("submit",B);d.addEventListener("click",D);async function B(t){if(t.preventDefault(),l=L.elements["search-text"].value.trim(),c=1,!l){n.warning({message:"Please enter a search query",position:"topRight"});return}R(),y(d),$();try{const{hits:r,totalHits:i}=await m(l,c,u);if(b=i,!r.length){n.info({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}p(r),i>u?O(d):n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{n.error({message:"Something went wrong. Please try again.",position:"topRight"})}finally{x()}}async function D(){c+=1,A();try{const{hits:t}=await m(l,c,u);p(t),c*u>=b&&(y(d),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const a=document.querySelectorAll(".gallery-item")[0].getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}catch{n.error({message:"Something went wrong while loading more.",position:"topRight"})}finally{I()}}
//# sourceMappingURL=index.js.map
