import{a as q,S as P,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const M="51455411-f57f23fa62a07ae8b27dc37d3",R="https://pixabay.com/api/";async function m(r,t=1,n=15){const s={key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n};try{return(await q.get(R,{params:s})).data}catch{throw new Error("Failed to fetch images from Pixabay")}}const f=document.querySelector(".gallery"),h=document.querySelector("span.loader"),$=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const t=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:i,comments:v,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${i}</p>
        <p><b>Comments:</b> ${v}</p>
        <p><b>Downloads:</b> ${S}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function x(){f.innerHTML=""}function p(){h.classList.remove("is-hidden")}function y(){h.classList.add("is-hidden")}const b=document.querySelector(".form"),L=document.querySelector(".load-more-container"),A=document.querySelector(".load-more");let l="",c=1;const d=15;let u=0;b.addEventListener("submit",I);A.addEventListener("click",O);function E(){L.classList.remove("is-hidden")}function w(){L.classList.add("is-hidden")}async function I(r){if(r.preventDefault(),l=b.elements["search-text"].value.trim(),c=1,!l){a.warning({message:"Please enter a search query",position:"topRight"});return}x(),w(),p();try{const{hits:t,totalHits:n}=await m(l,c,d);if(u=n,!t.length){a.info({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}g(t),t.length<u?E():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{a.error({message:"Something went wrong. Please try again.",position:"topRight"})}finally{y()}}async function O(){c+=1,p();try{const{hits:r}=await m(l,c,d);g(r);const t=document.querySelectorAll(".gallery-item"),n=t[t.length-r.length];if(n){const e=n.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}c*d>=u&&(w(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({message:"Something went wrong while loading more.",position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
